Awesome books with ES6
AnicetFantomas/Awesome_Books pull request #5
Opened 2022-03-28 18:24 UTC by AnicetFantomas

in this pull request we performed :

- Use ES6 modules to write modular JavaScript.
- Learn how to use proper ES6 syntax.
- Understand improvements that ES6 brings to JavaScript.
- Use npm as software packages system.

2022-03-28 18:42 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @AnicetFantomas👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

## Required Changes ♻️
- [ ] For this project you are supposed to name the styles file called `index.css`. Please change your styles file name to `index.css` from `style.css`. 

### See the image for reference

![image](https://user-images.githubusercontent.com/83803414/160465159-f1e435da-8740-4149-86e8-bf10b804fdfc.png)

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-28 18:42 UTC, thecodechaser commented on main.js
- [ ] For this project you are supposed to name the entry point for your JavaScript code called `index.js`. Please change this file name to `index.js` from `main.js`. 

### See the image for reference

![image](https://user-images.githubusercontent.com/83803414/160464652-f00f4931-4ae9-4e3c-99ae-aaa0bad5a44f.png)

2022-03-28 19:49 UTC, BenMukebo requested changes
### Hi **@AnicetFantomas,**

Great job on making changes required by the previous reviewer 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Githubflow was correctly used.  ✔️   
- Good arrow syntax for functions implementation. ✔️ 

 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly, it will be great to add instructions on how to run the project in your README file. This includes `npm install` , `npm start` etc

Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-28 19:49 UTC, BenMukebo commented on index.html
> +        <div class="date"></div>
- [ ] Great job so far 👏🏻  However as required by the previous reviewer, Kindly change your style file name, rename it from `style.css` to `index.css` see the project requirement  ⬇️ 

![11111](https://user-images.githubusercontent.com/79058364/160474969-6e9e6ba1-4d7e-4525-ae9c-6ba4f4846fe9.png)

2022-03-29 09:09 UTC, elmar8287 approved these changes
Hi, @AnicetFantomas.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-29 09:11 UTC, merged